unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

bind r source-file ~/.tmux.conf

set -g base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
# Double click to select a word and copy it to pbcopy
bind-key -n DoubleClick1Pane \
    select-pane \; \
    copy-mode -M \; \
    send-keys -X select-word \; \
    run-shell -d 0.2 \; \
    send-keys -X copy-pipe-and-cancel "pbcopy"
# Triple click to select a line and copy it to pbcopy
bind-key -n TripleClick1Pane \
    select-pane \; \
    copy-mode -M \; \
    send-keys -X select-line \; \
    run-shell -d 0.2 \; \
    send-keys -X copy-pipe-and-cancel "pbcopy"

set -g history-limit 100000
set -g focus-events on
set -g mouse on

# COLORSCHEME: gruvbox dark
set -g status on
set -g status-style "bg=#3c3836,fg=#ebdbb2"
setw -g window-status-style "bg=#3c3836,fg=#a89984"
setw -g window-status-activity-style "bg=#3c3836,fg=#bdae93,underscore"
setw -g window-status-current-style "bg=#3c3836,fg=#fabd2f,bold"
setw -g window-status-last-style "bg=#3c3836,fg=#83a598"
set -g pane-active-border-style "fg=#d5c4a1"
set -g pane-border-style "fg=#3c3836"
set -g message-style "bg=#504945,fg=#ebdbb2"
set -g message-command-style "bg=#bdae93,fg=#3c3836"
set -g display-panes-active-colour "#d5c4a1"
set -g display-panes-colour "#3c3836"
setw -g clock-mode-colour "#83a598"
setw -g window-status-bell-style "bg=#fb4934,fg=#282828"
set -g status-justify left
set -g status-left-style none
set -g status-left-length 80
set -g status-right-style none
set -g status-right-length 80
setw -g window-status-separator "#[fg=#504945] │ "
set -g status-left "\
#[bg=#665c54,fg=#bdae93] #S \
#[bg=#3c3836,fg=#665c54,nobold,noitalics,nounderscore] "
set -g status-right "\
#[bg=#3c3836,fg=#504945,nobold,nounderscore,noitalics]\
#[bg=#504945,fg=#a89984] %Y-%m-%d  %H:%M \
#[bg=#504945,fg=#bdae93,nobold,noitalics,nounderscore]\
#[bg=#bdae93,fg=#3c3836] #h "
setw -g window-status-current-format "#I #W#{?window_zoomed_flag, *Z,}"
setw -g window-status-format "#I #W#{?window_last_flag,-,}"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
